[workspace]
changelog_path = "./CHANGELOG.md"
changelog_config = "cliff.toml"
release_always = false
semver_check = false
version_prefix_pattern = '\bratatui(?:-(core|crossterm|widgets|termwiz|termion|macros))?\s*-\s*'

git_release_body = """
{{ changelog | replace(from=" by @", to=" by ") }}
"""
